# Generated by Django 5.2.17 on 2026-09-22 20:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticRepresentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('CANDIDATE_PROFILE', 'CANDIDATE_PROFILE'), ('JOB_PROFILE', 'JOB_PROFILE'), ('EXPERIENCE', 'EXPERIENCE'), ('JOB_REQUIREMENT', 'JOB_REQUIREMENT'), ('SKILL', 'SKILL')], max_length=32)),
                ('entity_id', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('embedding', models.JSONField()),
                ('model', models.CharField(max_length=100)),
                ('dimensions', models.PositiveIntegerField()),
                ('version', models.CharField(max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='semantics_s_entity__0bb911_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'entity_id', 'model', 'version'), name='unique_semantic_representation_per_model_version')],
            },
        ),
    ]
