from enum import StrEnum


class RequirementType(StrEnum):
    REQUIRED_SKILL = "REQUIRED_SKILL"
    PREFERRED_SKILL = "PREFERRED_SKILL"
    EXPERIENCE = "EXPERIENCE"
    EDUCATION = "EDUCATION"
    CERTIFICATION = "CERTIFICATION"
    LANGUAGE = "LANGUAGE"
    RESPONSIBILITY = "RESPONSIBILITY"
    SENIORITY = "SENIORITY"
    OTHER = "OTHER"


class RequirementImportance(StrEnum):
    REQUIRED = "REQUIRED"
    PREFERRED = "PREFERRED"
