# Generated by Django 5.2.17 on 2026-09-23 04:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analyses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("engine_version", models.CharField(max_length=20)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MISSING_REQUIREMENT", "MISSING_REQUIREMENT"),
                            ("WEAK_EVIDENCE", "WEAK_EVIDENCE"),
                            ("UNDERREPRESENTED_SKILL", "UNDERREPRESENTED_SKILL"),
                            ("EXPERIENCE_CLARIFICATION", "EXPERIENCE_CLARIFICATION"),
                            ("KEYWORD_PLACEMENT", "KEYWORD_PLACEMENT"),
                            ("RESPONSIBILITY_ALIGNMENT", "RESPONSIBILITY_ALIGNMENT"),
                            ("CERTIFICATION_GAP", "CERTIFICATION_GAP"),
                            ("LANGUAGE_GAP", "LANGUAGE_GAP"),
                            ("SENIORITY_CLARIFICATION", "SENIORITY_CLARIFICATION"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "CRITICAL"),
                            ("HIGH", "HIGH"),
                            ("MEDIUM", "MEDIUM"),
                            ("LOW", "LOW"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[("HIGH", "HIGH"), ("MEDIUM", "MEDIUM"), ("LOW", "LOW")], max_length=16
                    ),
                ),
                (
                    "safety",
                    models.CharField(
                        choices=[
                            ("SAFE_TO_REPHRASE", "SAFE_TO_REPHRASE"),
                            ("SAFE_TO_REORDER", "SAFE_TO_REORDER"),
                            ("REQUIRES_CANDIDATE_CONFIRMATION", "REQUIRES_CANDIDATE_CONFIRMATION"),
                            ("NOT_SAFE_TO_AUTOMATE", "NOT_SAFE_TO_AUTOMATE"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("HIGH_IMPACT", "HIGH_IMPACT"),
                            ("MEDIUM_IMPACT", "MEDIUM_IMPACT"),
                            ("LOW_IMPACT", "LOW_IMPACT"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("summary", models.TextField()),
                ("reason", models.TextField()),
                ("suggested_action", models.TextField()),
                ("supporting_evidence", models.JSONField(blank=True, default=list)),
                ("current_state", models.CharField(blank=True, max_length=200, null=True)),
                ("target_state", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="analyses.analysis",
                    ),
                ),
                (
                    "related_requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="analyses.requirementevaluationrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [models.Index(fields=["analysis"], name="recommendat_analysi_f83a03_idx")],
            },
        ),
    ]
