# Generated by Django 5.2.17 on 2026-09-23 00:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_alter_evidence_extraction_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING', max_length=16)),
                ('engine_version', models.CharField(max_length=20)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('score_breakdown', models.JSONField(blank=True, null=True)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_as_candidate', to='documents.document')),
                ('job_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_as_job', to='documents.document')),
            ],
            options={
                'verbose_name_plural': 'analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementEvaluationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('REQUIRED_SKILL', 'REQUIRED_SKILL'), ('PREFERRED_SKILL', 'PREFERRED_SKILL'), ('EXPERIENCE', 'EXPERIENCE'), ('EDUCATION', 'EDUCATION'), ('CERTIFICATION', 'CERTIFICATION'), ('LANGUAGE', 'LANGUAGE'), ('RESPONSIBILITY', 'RESPONSIBILITY'), ('SENIORITY', 'SENIORITY'), ('OTHER', 'OTHER')], max_length=20)),
                ('priority', models.CharField(choices=[('MANDATORY', 'MANDATORY'), ('PREFERRED', 'PREFERRED'), ('OPTIONAL', 'OPTIONAL')], max_length=16)),
                ('raw_text', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('MET', 'MET'), ('PARTIALLY_MET', 'PARTIALLY_MET'), ('NOT_MET', 'NOT_MET'), ('UNKNOWN', 'UNKNOWN')], max_length=16)),
                ('match_signal', models.CharField(choices=[('EXACT_MATCH', 'EXACT_MATCH'), ('ALIAS_MATCH', 'ALIAS_MATCH'), ('RELATED_MATCH', 'RELATED_MATCH'), ('SEMANTIC_MATCH', 'SEMANTIC_MATCH'), ('PARTIAL_MATCH', 'PARTIAL_MATCH'), ('NO_EVIDENCE', 'NO_EVIDENCE')], max_length=16)),
                ('match_strength', models.CharField(choices=[('NONE', 'NONE'), ('WEAK', 'WEAK'), ('PARTIAL', 'PARTIAL'), ('GOOD', 'GOOD'), ('STRONG', 'STRONG')], max_length=16)),
                ('score', models.FloatField()),
                ('confidence', models.FloatField()),
                ('matched_skill', models.CharField(blank=True, max_length=100, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_evaluations', to='analyses.analysis')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['candidate_document', 'job_document'], name='analyses_an_candida_41f048_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['status'], name='analyses_an_status_b5c59e_idx'),
        ),
    ]
