# Generated by Django 5.2.17 on 2026-09-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree_level',
            field=models.CharField(blank=True, choices=[('HIGH_SCHOOL', 'HIGH_SCHOOL'), ('ASSOCIATE', 'ASSOCIATE'), ('BACHELOR', 'BACHELOR'), ('MASTER', 'MASTER'), ('DOCTORATE', 'DOCTORATE'), ('PROFESSIONAL_CERTIFICATE', 'PROFESSIONAL_CERTIFICATE'), ('UNKNOWN', 'UNKNOWN')], help_text='Normalized from `degree` - see domain/cv/education_normalization.py.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='seniority',
            field=models.CharField(blank=True, choices=[('INTERN', 'INTERN'), ('JUNIOR', 'JUNIOR'), ('MID', 'MID'), ('SENIOR', 'SENIOR'), ('LEAD', 'LEAD'), ('MANAGER', 'MANAGER'), ('DIRECTOR', 'DIRECTOR'), ('EXECUTIVE', 'EXECUTIVE'), ('UNKNOWN', 'UNKNOWN')], help_text='Normalized from `title` - see domain/cv/seniority.py.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='canonical_name',
            field=models.CharField(blank=True, help_text='Normalized from `name` - see domain/cv/language_normalization.py.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='proficiency_normalized',
            field=models.CharField(blank=True, choices=[('BEGINNER', 'BEGINNER'), ('ELEMENTARY', 'ELEMENTARY'), ('INTERMEDIATE', 'INTERMEDIATE'), ('UPPER_INTERMEDIATE', 'UPPER_INTERMEDIATE'), ('ADVANCED', 'ADVANCED'), ('FLUENT', 'FLUENT'), ('NATIVE', 'NATIVE'), ('UNKNOWN', 'UNKNOWN')], max_length=20, null=True),
        ),
    ]
