# Generated by Django 5.2.17 on 2026-09-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_semantic_enrichment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False, help_text="True when end_date_raw is a 'still ongoing' marker (Present/actuel/...) - see infrastructure/document_processing/extraction/candidate_extractor.py::_is_current_marker."),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
