# Generated by Django 5.2.17 on 2026-09-24 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_education_location_experience_is_current_and_more'),
        ('documents', '0003_alter_evidence_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.evidence'),
        ),
    ]
