# Generated by Django 5.2.17 on 2026-09-22 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('PROGRAMMING_LANGUAGE', 'PROGRAMMING_LANGUAGE'), ('FRAMEWORK', 'FRAMEWORK'), ('LIBRARY', 'LIBRARY'), ('DATABASE', 'DATABASE'), ('CLOUD', 'CLOUD'), ('DEVOPS', 'DEVOPS'), ('DATA', 'DATA'), ('AI_ML', 'AI_ML'), ('WEB', 'WEB'), ('MOBILE', 'MOBILE'), ('TESTING', 'TESTING'), ('SOFTWARE', 'SOFTWARE'), ('METHODOLOGY', 'METHODOLOGY'), ('TOOL', 'TOOL')], max_length=32)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='skills.skill')),
                ('related_skills', models.ManyToManyField(blank=True, to='skills.skill')),
            ],
            options={
                'ordering': ['canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='skills.skill')),
            ],
        ),
    ]
