# Generated by Django 5.2.17 on 2026-09-22 19:57
#
# Phase 3: adds ecosystem/description/typed relations to the skill
# taxonomy (schema changes above, generated) and backfills them from
# domain/skills/taxonomy.py (data migration below, hand-written -
# mirrors 0002_seed_skill_taxonomy.py's two-pass approach: skills already
# exist from 0002, so this pass only sets the new fields and creates
# SkillRelation rows). `related_skills` is dropped because it was never
# populated by the taxonomy - Phase 2 defined it but no seed skill ever
# set it, so there is no data to preserve.

import django.db.models.deletion
from django.db import migrations, models

from domain.skills.taxonomy import SEED_SKILLS


def backfill_relationship_fields(apps, schema_editor):
    Skill = apps.get_model("skills", "Skill")
    SkillRelation = apps.get_model("skills", "SkillRelation")

    by_name = {skill.canonical_name: skill for skill in Skill.objects.all()}

    for entry in SEED_SKILLS:
        row = by_name.get(entry.canonical_name)
        if row is None:
            continue
        row.ecosystem = entry.ecosystem
        row.description = entry.description
        row.save(update_fields=["ecosystem", "description"])

    for entry in SEED_SKILLS:
        from_row = by_name.get(entry.canonical_name)
        if from_row is None:
            continue
        for relation in entry.relations:
            to_row = by_name.get(relation.target_skill)
            if to_row is None:
                continue
            SkillRelation.objects.get_or_create(
                from_skill=from_row, to_skill=to_row, relation_type=relation.relation_type.value
            )


def clear_relationship_fields(apps, schema_editor):
    Skill = apps.get_model("skills", "Skill")
    SkillRelation = apps.get_model("skills", "SkillRelation")
    SkillRelation.objects.all().delete()
    Skill.objects.update(ecosystem=None, description=None)


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_seed_skill_taxonomy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='related_skills',
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='ecosystem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SkillRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('PARENT_OF', 'PARENT_OF'), ('CHILD_OF', 'CHILD_OF'), ('PART_OF_ECOSYSTEM', 'PART_OF_ECOSYSTEM'), ('RELATED_TO', 'RELATED_TO'), ('ALTERNATIVE_TO', 'ALTERNATIVE_TO'), ('BUILDS_ON', 'BUILDS_ON')], max_length=20)),
                ('from_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='skills.skill')),
                ('to_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='skills.skill')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_skill', 'to_skill', 'relation_type'), name='unique_skill_relation')],
            },
        ),
        migrations.RunPython(backfill_relationship_fields, clear_relationship_fields),
    ]
