# Generated by Django 5.2.17 on 2026-09-22 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('seniority', models.CharField(blank=True, max_length=50, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_profile', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('REQUIRED_SKILL', 'REQUIRED_SKILL'), ('PREFERRED_SKILL', 'PREFERRED_SKILL'), ('EXPERIENCE', 'EXPERIENCE'), ('EDUCATION', 'EDUCATION'), ('CERTIFICATION', 'CERTIFICATION'), ('LANGUAGE', 'LANGUAGE'), ('RESPONSIBILITY', 'RESPONSIBILITY'), ('SENIORITY', 'SENIORITY'), ('OTHER', 'OTHER')], max_length=20)),
                ('importance', models.CharField(choices=[('REQUIRED', 'REQUIRED'), ('PREFERRED', 'PREFERRED')], max_length=16)),
                ('raw_text', models.CharField(max_length=300)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.evidence')),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='jobs.jobprofile')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='skills.skill')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
