# Generated by Django 5.2.17 on 2026-09-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='seniority_normalized',
            field=models.CharField(blank=True, choices=[('INTERN', 'INTERN'), ('JUNIOR', 'JUNIOR'), ('MID', 'MID'), ('SENIOR', 'SENIOR'), ('LEAD', 'LEAD'), ('MANAGER', 'MANAGER'), ('DIRECTOR', 'DIRECTOR'), ('EXECUTIVE', 'EXECUTIVE'), ('UNKNOWN', 'UNKNOWN')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='minimum_years',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Parsed from raw_text when requirement_type is EXPERIENCE.', null=True),
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='normalized_value',
            field=models.CharField(blank=True, help_text='A normalized reading of raw_text (e.g. an EducationLevel) when applicable.', max_length=100, null=True),
        ),
    ]
