"""Local filesystem FileStorage implementation for development (section 35).

Not a public download endpoint - see docs/architecture/phase-2-pipeline.md
"Storage & access" section. Nothing in interfaces/api exposes these paths
directly; the API only ever returns document metadata, never a raw file
URL, per the Phase 2 security baseline (section 59).
"""
from pathlib import Path

from django.conf import settings


class LocalFileStorage:
    """Implements infrastructure.storage.base.FileStorage."""

    def __init__(self, base_dir: Path | None = None) -> None:
        self._base_dir = base_dir or Path(settings.MEDIA_ROOT) / "documents"

    def save(self, content: bytes, key: str) -> str:
        destination = self._resolve(key)
        destination.parent.mkdir(parents=True, exist_ok=True)
        if not destination.exists():
            destination.write_bytes(content)
        return key

    def read(self, reference: str) -> bytes:
        path = self._resolve(reference)
        if not path.exists():
            raise FileNotFoundError(f"No stored file for reference: {reference}")
        return path.read_bytes()

    def delete(self, reference: str) -> None:
        path = self._resolve(reference)
        path.unlink(missing_ok=True)

    def _resolve(self, key: str) -> Path:
        # `key` is always generated by our own code (file_hash-based, see
        # application/documents/upload_document.py) - never taken
        # verbatim from user input - but guard against path traversal
        # regardless, since a corrupted key should fail loudly, not read
        # outside base_dir.
        resolved = (self._base_dir / key).resolve()
        if self._base_dir.resolve() not in resolved.parents and resolved != self._base_dir.resolve():
            raise ValueError(f"Invalid storage key: {key}")
        return resolved
