# Generated by Django 5.2.17 on 2026-09-22 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('CV', 'CV'), ('JOB_OFFER', 'JOB_OFFER')], max_length=16)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=127)),
                ('file_size', models.PositiveIntegerField()),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('storage_reference', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('UPLOADED', 'UPLOADED'), ('VALIDATING', 'VALIDATING'), ('PROCESSING', 'PROCESSING'), ('PROCESSED', 'PROCESSED'), ('FAILED', 'FAILED')], default='UPLOADED', max_length=16)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('sections', models.JSONField(blank=True, null=True)),
                ('processing_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, choices=[('SUMMARY', 'SUMMARY'), ('EXPERIENCE', 'EXPERIENCE'), ('EDUCATION', 'EDUCATION'), ('SKILLS', 'SKILLS'), ('PROJECTS', 'PROJECTS'), ('CERTIFICATIONS', 'CERTIFICATIONS'), ('LANGUAGES', 'LANGUAGES'), ('ACHIEVEMENTS', 'ACHIEVEMENTS'), ('PUBLICATIONS', 'PUBLICATIONS'), ('VOLUNTEER_EXPERIENCE', 'VOLUNTEER_EXPERIENCE'), ('RESPONSIBILITIES', 'RESPONSIBILITIES'), ('REQUIREMENTS', 'REQUIREMENTS'), ('OTHER', 'OTHER')], max_length=32, null=True)),
                ('text', models.TextField()),
                ('start_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('end_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence', models.FloatField()),
                ('extraction_method', models.CharField(choices=[('PARSER', 'PARSER'), ('RULE', 'RULE'), ('REGEX', 'REGEX'), ('MANUAL', 'MANUAL'), ('LLM', 'LLM'), ('HYBRID', 'HYBRID')], max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='documents.document')),
            ],
            options={
                'verbose_name_plural': 'evidence records',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_hash', 'document_type'], name='documents_d_file_ha_338386_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
    ]
