# Generated by Django 5.2.17 on 2026-09-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='extraction_method',
            field=models.CharField(choices=[('PARSER', 'PARSER'), ('RULE', 'RULE'), ('REGEX', 'REGEX'), ('ALIAS', 'ALIAS'), ('TAXONOMY', 'TAXONOMY'), ('EMBEDDING', 'EMBEDDING'), ('MANUAL', 'MANUAL'), ('LLM', 'LLM'), ('HYBRID', 'HYBRID')], max_length=16),
        ),
    ]
