# Generated by Django 5.2.17 on 2026-09-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_evidence_extraction_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='section',
            field=models.CharField(blank=True, choices=[('PERSONAL_INFORMATION', 'PERSONAL_INFORMATION'), ('SUMMARY', 'SUMMARY'), ('HIGHLIGHTS', 'HIGHLIGHTS'), ('CORE_QUALIFICATIONS', 'CORE_QUALIFICATIONS'), ('EXPERIENCE', 'EXPERIENCE'), ('EDUCATION', 'EDUCATION'), ('PROJECTS', 'PROJECTS'), ('SKILLS', 'SKILLS'), ('TECHNICAL_SKILLS', 'TECHNICAL_SKILLS'), ('CERTIFICATIONS', 'CERTIFICATIONS'), ('LANGUAGES', 'LANGUAGES'), ('ACHIEVEMENTS', 'ACHIEVEMENTS'), ('PUBLICATIONS', 'PUBLICATIONS'), ('PRESENTATIONS', 'PRESENTATIONS'), ('VOLUNTEER_EXPERIENCE', 'VOLUNTEER_EXPERIENCE'), ('LEADERSHIP', 'LEADERSHIP'), ('INTERESTS', 'INTERESTS'), ('HOBBIES', 'HOBBIES'), ('AFFILIATIONS', 'AFFILIATIONS'), ('SCHOLARSHIPS', 'SCHOLARSHIPS'), ('ADDITIONAL_INFORMATION', 'ADDITIONAL_INFORMATION'), ('RESPONSIBILITIES', 'RESPONSIBILITIES'), ('REQUIREMENTS', 'REQUIREMENTS'), ('OTHER', 'OTHER')], max_length=32, null=True),
        ),
    ]
