# Generated by Django 5.2.17 on 2026-09-23 04:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analyses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TailoringPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("CONSERVATIVE", "CONSERVATIVE"), ("AGGRESSIVE_SAFE", "AGGRESSIVE_SAFE")],
                        max_length=20,
                    ),
                ),
                ("engine_version", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("PLANNING", "PLANNING"),
                            ("GENERATING", "GENERATING"),
                            ("VALIDATING", "VALIDATING"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("operations", models.JSONField(blank=True, default=list)),
                ("protected_fact_ids", models.JSONField(blank=True, default=list)),
                ("before_score", models.FloatField(blank=True, null=True)),
                ("after_score", models.FloatField(blank=True, null=True)),
                ("requirements_improved", models.IntegerField(default=0)),
                ("requirements_unchanged", models.IntegerField(default=0)),
                ("requirements_still_missing", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tailoring_plans",
                        to="analyses.analysis",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TailoringChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fact_id", models.CharField(max_length=100)),
                ("recommendation_title", models.CharField(max_length=300)),
                ("original_text", models.TextField()),
                ("final_text", models.TextField()),
                ("diff", models.JSONField(blank=True, default=list)),
                ("accepted", models.BooleanField()),
                ("rejection_reasons", models.JSONField(blank=True, default=list)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="tailoring.tailoringplan",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="tailoringplan",
            index=models.Index(fields=["analysis"], name="tailoring_t_analysi_312a57_idx"),
        ),
        migrations.AddIndex(
            model_name="tailoringplan",
            index=models.Index(fields=["status"], name="tailoring_t_status_7f3c80_idx"),
        ),
    ]
